### ISSUE TITLE
Error: SQLite: file is not a database

### ISSUE THREAD

**Issue by slowkow** [phiresky/sql.js-httpvfs#11]
I tried to follow your instructions with the example, but it doesn't seem to work for me.

Sorry if I'm missing something obvious here... I'm not an expert with all the tools involved.

Could I please ask if you might have any ideas about how I can work around this error?

Thanks for any help you can provide!

# Error

Here's the error I get when I try to open the `example/index.html` page in Google Chrome:

```
constructing url database /example.sqlite3
c356a8c1ca29f8b1b394.js:1 filename _example.sqlite3
c356a8c1ca29f8b1b394.js:1 constructing url database /example.sqlite3 filename _example.sqlite3
c356a8c1ca29f8b1b394.js:1 [xhr of size 4 KiB @ 0 KiB]
index.ts:20 Uncaught (in promise) Error: SQLite: file is not a database
    at te.Z.handleError (c356a8c1ca29f8b1b394.js:1)
    at te.Z.exec (c356a8c1ca29f8b1b394.js:1)
    at Object.SplitFileHttpDatabase (c356a8c1ca29f8b1b394.js:1)
```

When I click to see the code that corresponds to this error, here is what I see:

```
if (this.db = new n.CustomDatabase(r),
    s) {
  const e = (await this.db.exec("pragma page_size; pragma cache_size=0"))[0].values[0][0];
  e !== s.requestChunkSize && console.warn(`Chunk size does not match page size: pragma page_size = ${e} but chunkSize = ${s.requestChunkSize}`)
}
```

# Steps

Here are all the steps I completed:

```
git clone https://github.com/phiresky/sql.js-httpvfs.git
cd example/
npm install --save-dev webpack webpack-cli typescript ts-loader http-server
npm install --save sql.js-httpvfs
./node_modules/.bin/webpack --mode=development
```

I'm using nginx to serve the `index.html` file. I had to modify the `/etc/nginx/nginx.conf` file with these 2 additions:

```
http {
    # ...
    include             /etc/nginx/mime.types;
    types {
        application/wasm wasm; # <-- addition 1
    }
    default_type        application/octet-stream;
    proxy_force_ranges on;     # <-- addition 2
    # ...
}
```

Versions:

```
$ npm --version
7.13.0

Google Chrome
Version 90.0.4430.212 (Official Build) (x86_64)
```

**Comment by HyperBCS** [comment]
A quick workaround for the issue would be to disable caching the xhr requests. This may not be ideal for many requests but it looks like the cached data may load incorrect.

Adding the following below `src/lazyFile.ts:232` fixed the issue for me
`xhr.setRequestHeader('Cache-Control', 'no-cache');`

**Comment by slowkow** [comment]
@HyperBCS Thanks for the reply!

I am not sure how to apply your patch to my current code ...

Here's the code you are proposing to change:

https://github.com/phiresky/sql.js-httpvfs/blob/852374bc0fcf84fd7844eadbd1aa074baeee21c9/src/lazyFile.ts#L229-L233

When I look inside my folder `example/node_modules`, I can't find the `lazyFile.ts` file:

```
$ ls -lah node_modules/sql.js-httpvfs/*
-rw-r--r--. 1 ks38 posixusers  12K Jul 30  2020 node_modules/sql.js-httpvfs/LICENSE
-rw-r--r--. 1 ks38 posixusers  864 May  8 05:47 node_modules/sql.js-httpvfs/package.json
-rw-r--r--. 1 ks38 posixusers 6.3K May  8 05:31 node_modules/sql.js-httpvfs/README.md

node_modules/sql.js-httpvfs/dist:
total 1.7M
drwxr-xr-x. 2 ks38 posixusers  229 May 24 11:55 .
drwxr-xr-x. 3 ks38 posixusers   70 May 24 11:55 ..
-rw-r--r--. 1 ks38 posixusers  540 May  8 04:46 db.d.ts
-rw-r--r--. 1 ks38 posixusers  121 May  8 04:46 index.d.ts
-rw-r--r--. 1 ks38 posixusers 7.8K May  8 05:18 index.js
-rw-r--r--. 1 ks38 posixusers  33K May  8 05:18 index.js.map
-rw-r--r--. 1 ks38 posixusers 2.2K May  8 04:46 lazyFile.d.ts
-rw-r--r--. 1 ks38 posixusers 1.8K May  8 04:46 sqlite.worker.d.ts
-rw-r--r--. 1 ks38 posixusers  86K May  8 05:46 sqlite.worker.js
-rw-r--r--. 1 ks38 posixusers 274K May  8 05:46 sqlite.worker.js.map
-rw-r--r--. 1 ks38 posixusers 1.3M May  8 05:15 sql-wasm.wasm
-rw-r--r--. 1 ks38 posixusers 1.8K May  8 04:46 util.d.ts
-rw-r--r--. 1 ks38 posixusers 5.2K May  8 04:46 vtab.d.ts
```

I was hoping to quickly modify one line in the source code to see if your proposed patch might help, but the `lazyFile.d.ts` file does not have the source code.

Do you know where node puts the `lazyFile.ts` file? What do you think is the best way to apply quick patches to the source code of app dependencies while we are developing the app?

Sorry for the basic questions, but I'm still learning how to deal with dependencies in javascript projects.

**Comment by phiresky** [comment]
The contents of lazyFile.ts will be contained within sqlite.worker.js probably, since the library is compiled with webpack. 


The `proxy_force_ranges`  shouldn't be needed, you should probably ensure your server sends the Accept-Ranges: bytes header instead.


Adding that header in the request doesn't really sound like the right solution though, since it seems like your server is just responding with the wrong data? So the answer to this depends on how your server works. I guess it's served from node or python or something?

**Comment by phiresky** [comment]
From [this article](https://www.nginx.com/blog/smart-efficient-byte-range-caching-nginx/) it also sounds like you need to take special care when you serve a file from a proxied upstream through nginx and have range requests

**Comment by slowkow** [comment]
> The proxy_force_ranges shouldn't be needed, you should probably ensure your server sends the Accept-Ranges: bytes header instead.

Here's what I see at http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_force_ranges

```
Syntax:	proxy_force_ranges on | off;
Default:	
proxy_force_ranges off;
Context:	http, server, location
This directive appeared in version 1.7.7.

Enables byte-range support for both cached and uncached responses from the
proxied server regardless of the “Accept-Ranges” field in these responses.
```

This stackoverflow post suggests that `proxy_force_ranges` might be necessary, but I am not certain.

https://stackoverflow.com/questions/22728016/nginx-is-not-accepting-range-of-bytes

The author of the question says that adding this to the nginx config did not help:

```
add_header Accept-Ranges bytes;
```

After adding this header to my nginx config, then I got a new error when I try to access `example/index.html`:

```
c356a8c1ca29f8b1b394.js:1 server does not support byte serving (`Accept-Ranges: bytes` header missing), or your database is hosted on CORS and the server doesn't mark the accept-ranges header as exposed seen response headers accept-ranges: bytes, bytes
content-length: 6131
content-type: text/html
date: Tue, 25 May 2021 14:32:45 GMT
etag: "60370703-17f3"
last-modified: Thu, 25 Feb 2021 02:10:11 GMT
server: nginx/1.16.1
```

After deleting the `add_header` line, then the error goes away.


> I guess it's served from node or python or something?

I use nginx to serve all of the files, without using node or python or anything else. Is it necessary to use node as the server for an app that uses `sql.js-httpvfs`?

**Comment by slowkow** [comment]
Oh my, the situation is even more complicated. It matters which `server {}` block you add the header to. In my case, I added the `add_header` line to the **https** server block, and this caused the new error. If I instead add the line to the **http** (not https) server block, then the error goes away.

Anyway, I believe that we do not need the `add_header` line, because this is what I see in the Chrome console:

<img width=50% src="https://user-images.githubusercontent.com/209714/119519074-1e15b980-bd47-11eb-8de3-1d3667b41270.png">

<img width=50% src="https://user-images.githubusercontent.com/209714/119519079-1f46e680-bd47-11eb-9393-437ec300ad6a.png">


I'm glad that I looked at this, because it is clearly showing the wrong URL!

There is no `example.sqlite3` file at the root URL `https://myurl.edu/example.sqlite3`.

Instead, my file is available at `https://myurl.edu/some/long/path/example/example.sqlite3`

So, I changed the file `src/index.ts` to this:

```
async function load() {
  const worker = await createDbWorker(
    [
      {
        from: "inline",
        config: {
          serverMode: "full",
          # url: "/example.sqlite3",
          url: "/some/long/path/example/example.sqlite3",
          requestChunkSize: 4096,
        },
      },
    ],
    workerUrl.toString(),
    wasmUrl.toString()
  );

  const result = await worker.db.query(`select * from mytable`);

  document.body.textContent = JSON.stringify(result);
}
```

And now it works! Hooray! 🎉

I will keep trying to hack on my project and see what I can do next... thanks so much for sharing this library, @phiresky !

Do you think it might be possible to change the `index.ts` code to allow relative urls instead of requiring the user to specify the full path to the sqlite file?

**Comment by phiresky** [comment]
> I use nginx to serve all of the files

I assumed you were using some backend because the proxy_* headers are only used when you have serve the files from a different server, and because nginx by default does everything correctly to work with sql.js-httpvfs - so you shouldn't use add_header or anything at all with nginx, because it understands and correctly serves range requests without any changes.

> Do you think it might be possible to change the index.ts code to allow relative urls instead of requiring the user to specify the full path to the sqlite file?

I'm not actually sure why it doesn't interpret the relative urls "correctly", it should interpret them relative to your index.html

**Comment by phiresky** [comment]
Yeah, you shouldn't place stuff into your dist folder. But then I think this is not an issue since relative URLs work as they should. You could use e.g. url: "../example.sqlite3" but it will always be relative to the url base of the document you open
