### ISSUE TITLE
The library doesn't work after upgrading to `0.8.10`

### ISSUE THREAD

**Issue by nooreldeensalah** [phiresky/sql.js-httpvfs#17]
Hi,

I was recently working with the library, but I noticed that version `0.8.10` is not working and returns errors in some cases.

To reproduce the bug you have to install version `0.8.10`.

`npm install sql.js-httpvfs@0.8.10`

clone the repository and bundle the example, it will return an empty array `[]` instead of `[{"foo":"hello","bar":"world"}]`,

Also wanted to point out that, in the case of `*.db` files (mine was generated by a sql-alchemy schema) I got an error that stated that the database disk image is malformed as can be seen from the photo below:
![image](https://user-images.githubusercontent.com/61914159/131193395-82dba311-02df-4c67-8746-99e82814904b.png)

**Note**: I got ~~not~~ no errors with my sql-alchemy schema generated database when I tested with `0.8.9` and it worked fine, and I also tested the attached example with `0.8.9` and it returned that data, not an empty array.

It seems like version `0.8.10` is still a work in progress, but it can be installed from npm registry.

Regards,

**Comment by phiresky** [comment]
Thanks, for letting me know. This was indeed a regression (for some use cases) I introduced when i fixed #13. Should be fixed in 0.8.11
