### ISSUE TITLE
browser hanging on webworker instantiation

### ISSUE THREAD

**Issue by hcliff** [phiresky/sql.js-httpvfs#25]
Hey there, thanks for writing this lib, it's very cool!

I'm trying to use your modified sql.js implementation more directly, but curiously the call to `initSqlJs` with `locateFile` set to the httpvfs sql.js version causes the browser to hang. Using the original repos implementation doesn't.

this hangs (as does serving the file myself locally)
```
const SQL = await initSqlJs({ 
        locateFile: file => {
            return 'https://phiresky.github.io/blog/sql-wasm.wasm';
        }
});
```

this does not 
```
const SQL = await initSqlJs({ 
        locateFile: file => {
           return `https://sql.js.org/dist/sql-wasm.wasm`;
        }
});
```

there's nothing obvious in the additional commits in the https://github.com/phiresky/sql.js repo - am I missing something? thanks!

**Comment by phiresky** [comment]
It's not possible to use the wasm file directly with the original sql.js version. It has to be used through webworkers as implemented in the library itself, since the VFS callbacks need to be handled synchronously.
