### ISSUE TITLE
Can the results be iterated over while the request is in progress?

### ISSUE THREAD

**Issue by Tails** [phiresky/sql.js-httpvfs#27]
It seems wa-sqlite has this feature where you provide a callback to iterate over the results while the query is in progress. 

Is that also possible with sql.js-httpvfs?

**Comment by phiresky** [comment]
It would be technically feasible to implement it, but it's not possible right now. Implementing the httpvfs functionality on top of wa-sqlite should be fairly easy though.

**Comment by phiresky** [comment]
Closing since I have no plans on continuing adding features to sql.js-httpvfs, since the base is pretty hacky and reimplementing on top of a cleaner base would be preferrable.
