### ISSUE TITLE
Amazon S3?

### ISSUE THREAD

**Issue by chrisspen** [phiresky/sql.js-httpvfs#34]
Does this work with a distributed static filesystem like Amazon's S3?

**Comment by phiresky** [comment]
Yes, whenever the backend supports range requests (which should be the case for S3). But the performance will vary depending on how the backend does caching, which is hard to find out except by trying it

**Comment by chrisspen** [comment]
Interesting. I guess technically I'm asking about content hosted on Cloudfront pulling data from S3.

Based on [these docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RangeGETs.html), it sounds like Cloudfront supports range requests as well, as long as the origin (in this case S3), also supports them, right?

**Comment by chrisspen** [comment]
Confirmed it works fairly well on S3+Cloudfront.
