### ISSUE TITLE
Does this vfs support update, delete and insert?

### ISSUE THREAD

**Issue by brook-w** [phiresky/sql.js-httpvfs#41]
I have installed dependency, but it seems that there is only one `query()` operation. In fact, I have not understood its working principle. If only there was a more detailed introduction. Now it seems that there is only one `example` of `query`

**Comment by bew** [comment]
Introductory blog post was this: https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/
Definitely worth a read!

I also think it would help to put the link in the readme, near the beginning
